require("nvim-tree").setup({
    renderer={
        group_empty=true,
        icons={
            show={
                file=false,
                folder=false,
                folder_arrow=false,
                git=false,
            },
        },
    },
    filters={
        dotfiles=false,
    },
})
